name: KillStreak
main: io.github.pure1.killstreak.killStreak
commands:
  KillStreak:
    description: Shows Kill Streak help.
    aliases: [ks]
permissions:
  KillStreak.*:
    description: Gives access to all Kill Streak Commands
version: 1.0



