name: KillStreak
main: io.github.pure1.killstreak.killStreak
commands:
  KillStreak:
    description: Shows Kill Streak help.
    aliases: [ks]
permissions:
  killstreak.*:
    description: Gives access to all Kill Streak Commands
    children:
      killstreak.killstreak: true
      killstreak.player: true
      killstreak.config.*: true
      killstreak.kills.*: true
      killstreak.help: true
      killstreak.kill: true

  killstreak.killstreak:
    description: Gives access to the /killstreak command
    default: true
  killstreak.player:
    description: Gives access to the /killstreak [player] command
    default: true
  killstreak.help:
    description: Gives access to the /killstreak help command
    default: true
  killstreak.kill:
    description: Gives a player the ability to gain kills
    default: true
  
  
  killstreak.config.*:
    description: Gives access to all /killstreak config Commands
    children:
      killstreak.config.help: true
      killstreak.config.get: true
      killstreak.config.set: true
      killstreak.config.commands.*: true
      
  killstreak.config.help:
    description: Gives access to the /killstreak config command
    default: false
  killstreak.config.get:
    description: Gives access to the /killstreak config get command
    default: false
  killstreak.config.set:
    description: Gives access to the /killstreak config set command
    default: false
    
    
  killstreak.config.commands.*:
    description: Gives access all /killstreak config commands commands
    children:
      killstreak.config.commands.get: true
      killstreak.config.commands.set: true
      killstreak.config.commands.add: true
      killstreak.config.commands.remove: true
      killstreak.config.commands.help: true
  
  killstreak.config.commands.get:
    description: gives access to the /killstreak config commands get command
    default: false
  killstreak.config.commands.set:
    description: gives access to the /killstreak config commands set command
    default: false
  killstreak.config.commands.add:
    description: gives access to the /killstreak config commands add command
    default: false
  killstreak.config.commands.remove:
    description: gives access to the /killstreak config commands remove command
    default: false
  killstreak.config.commands.remove:
    description: gives access to the /killstreak config commands command
    default: false
      
      
  killstreak.kills.*:
    description: Gives access to all /killstreak kills Commands
    children:
      killstreak.kills.help: true
      killstreak.kills.set: true
      killstreak.kills.add: true
      killstreak.config.remove: true
      
  killstreak.kills.help:
    description: gives access to the /killstreak kills command
    default: false
  killstreak.kills.set:
    description: gives access to the /killstreak kills set command
    default: false
  killstreak.kills.add:
    description: gives access to the /killstreak kills add command
    default: false
  killstreak.config.remove:
    description: gives access to the /killstreak kills remove command
    default: false
  
version: 0.1.1



